INFO:Controller: =====> Starting BigSwitch Controller <===== 
INFO:Controller:Launching controller c1: ./start_vms -d /home-local/andrewor/work -h -r
[1;41m[1;33m[c1] Traceback (most recent call last):[1;m

[1;41m[1;33m[c1]   File "/home-local/andrewor/work/ve/bin/bt", line 7, in <module>[1;m

[1;41m[1;33m[c1]     execfile(__file__)[1;m

[1;41m[1;33m[c1]   File "/mnt/blade-0-b/home-local/andrewor/work/bigswitchcontroller/bigtest/bt", line 2478, in <module>[1;m

[1;41m[1;33m[c1]     main(sys.argv[1:])[1;m

[1;41m[1;33m[c1]   File "/mnt/blade-0-b/home-local/andrewor/work/bigswitchcontroller/bigtest/bt", line 2475, in main[1;m

[1;41m[1;33m[c1]     commands[command](args[1:])[1;m

[1;41m[1;33m[c1]   File "/mnt/blade-0-b/home-local/andrewor/work/bigswitchcontroller/bigtest/bt", line 2285, in showCommand[1;m

[1;41m[1;33m[c1]     for l in node.dump().getvalue().split("\n")[:-1]:[1;m

[1;41m[1;33m[c1]   File "/home-local/andrewor/work/bigswitchcontroller/bigtest/node.py", line 399, in dump[1;m

[1;41m[1;33m[c1]     pid = self.pid()[1;m

[1;41m[1;33m[c1]   File "/home-local/andrewor/work/bigswitchcontroller/bigtest/node.py", line 319, in pid[1;m

[1;41m[1;33m[c1]     return bigtest.readPidFile(os.path.join(self.statedir_, "pid"))[1;m

[1;41m[1;33m[c1]   File "/home-local/andrewor/work/bigswitchcontroller/bigtest/__init__.py", line 144, in readPidFile[1;m

[1;41m[1;33m[c1]     return int(file(pidFile).read().strip())[1;m

[1;41m[1;33m[c1] IOError: [Errno 13] Permission denied: '/var/run/bigtest/node-node1/pid'[1;m

[1;41m[1;33m[c1] make: *** [show-vms] Error 1[1;m

[1;33m[c1] No vm found; starting new one(s)![1;m

Caught signal 2, stopping sdndebug (pid 727)
